apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyter-rolebinding
  namespace: jupyter
subjects:
  - kind: ServiceAccount
    name: jupyter-sa
    namespace: jupyter
roleRef:
  kind: ClusterRole
  name: jupyter-role
  apiGroup: rbac.authorization.k8s.io